<?php

declare(strict_types=1);

return [
    'http://www.w3.org/2001/XMLSchema' => [
        'all' => '\SimpleSAML\XMLSchema\XML\xs\All',
        'annotation' => '\SimpleSAML\XMLSchema\XML\xs\Annotation',
        'any' => '\SimpleSAML\XMLSchema\XML\xs\Any',
        'anyAttribute' => '\SimpleSAML\XMLSchema\XML\xs\AnyAttribute',
        'appinfo' => '\SimpleSAML\XMLSchema\XML\xs\Appinfo',
        'attribute' => '\SimpleSAML\XMLSchema\XML\xs\TopLevelAttribute',
        'attributeGroup' => '\SimpleSAML\XMLSchema\XML\xs\NamedAttributeGroup',
        'choice' => '\SimpleSAML\XMLSchema\XML\xs\Choice',
        'complexContent' => '\SimpleSAML\XMLSchema\XML\xs\ComplexContent',
        'complexType' => '\SimpleSAML\XMLSchema\XML\xs\TopLevelComplexType',
        'documentation' => '\SimpleSAML\XMLSchema\XML\xs\Documentation',
        'element' => '\SimpleSAML\XMLSchema\XML\xs\TopLevelElement',
        'enumeration' => '\SimpleSAML\XMLSchema\XML\xs\Enumeration',
        'field' => '\SimpleSAML\XMLSchema\XML\xs\Field',
        'fractionDigits' => '\SimpleSAML\XMLSchema\XML\xs\FractionDigits',
        'group' => '\SimpleSAML\XMLSchema\XML\xs\NamedGroup',
        'import' => '\SimpleSAML\XMLSchema\XML\xs\Import',
        'include' => '\SimpleSAML\XMLSchema\XML\xs\XsInclude',
        'key' => '\SimpleSAML\XMLSchema\XML\xs\Key',
        'keyref' => '\SimpleSAML\XMLSchema\XML\xs\Keyref',
        'length' => '\SimpleSAML\XMLSchema\XML\xs\Length',
        'list' => '\SimpleSAML\XMLSchema\XML\xs\XsList',
        'maxExclusive' => '\SimpleSAML\XMLSchema\XML\xs\MaxExclusive',
        'maxInclusive' => '\SimpleSAML\XMLSchema\XML\xs\MaxInclusive',
        'maxLength' => '\SimpleSAML\XMLSchema\XML\xs\MaxLength',
        'minExclusive' => '\SimpleSAML\XMLSchema\XML\xs\MinExclusive',
        'minInclusive' => '\SimpleSAML\XMLSchema\XML\xs\MinInclusive',
        'minLength' => '\SimpleSAML\XMLSchema\XML\xs\MinLength',
        'notation' => '\SimpleSAML\XMLSchema\XML\xs\Notation',
        'pattern' => '\SimpleSAML\XMLSchema\XML\xs\Pattern',
        'redefine' => '\SimpleSAML\XMLSchema\XML\xs\Redefine',
        'restriction' => '\SimpleSAML\XMLSchema\XML\xs\Restriction',
        'schema' => '\SimpleSAML\XMLSchema\XML\xs\Schema',
        'selector' => '\SimpleSAML\XMLSchema\XML\xs\Selector',
        'sequence' => '\SimpleSAML\XMLSchema\XML\xs\Sequence',
        'simpleContent' => '\SimpleSAML\XMLSchema\XML\xs\SimpleContent',
        'simpleType' => '\SimpleSAML\XMLSchema\XML\xs\TopLevelSimpleType',
        'totalDigits' => '\SimpleSAML\XMLSchema\XML\xs\TotalDigits',
        'union' => '\SimpleSAML\XMLSchema\XML\xs\Union',
        'unique' => '\SimpleSAML\XMLSchema\XML\xs\Unique',
        'whiteSpace' => '\SimpleSAML\XMLSchema\XML\xs\WhiteSpace',
    ],
];
